### ISSUE TITLE
cargo run crashes without user-friendly message about absence of hellcheck.yml

### ISSUE THREAD

**Issue by zekefast** [greyblake/hellcheck#3]
# Actual result

`cargo run` panics without user-friendly message:

```
$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.23s                                                                                                                
     Running `target/debug/hellcheck`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
Here is the results with `RUST_BACKTRACE=1`:

```
$ RUST_BACKTRACE=1 cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.20s                                                                                                                
     Running `target/debug/hellcheck`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:1009:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:476
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::result::unwrap_failed
             at libcore/macros.rs:26
   9: <core::result::Result<T, E>>::unwrap
             at libcore/result.rs:808
  10: hellcheck::load_config
             at src/lib.rs:26
  11: hellcheck::run
             at src/lib.rs:57
  12: hellcheck::main
             at src/main.rs:6
  13: std::rt::lang_start::{{closure}}
             at libstd/rt.rs:74
  14: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  15: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  16: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  17: std::rt::lang_start
             at libstd/rt.rs:74
  18: main
  19: __libc_start_main
  20: _start
```

# Expected result

Output user-friendly message about absence of `hellcheck.yml`.

# Steps to reproduce

* `git clone --recursive git@github.com:greyblake/hellcheck.git`
* `cd hellcheck`
* `cargo run`

# Environment
* rustc: `1.31.1`
* cargo: `1.31.0`
* platform: `Linux somehostname 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux`

# Note
I would suggest to use [`expect()`](https://doc.rust-lang.org/std/option/enum.Option.html#method.expect) instead of `unwrap()` in situations like [`let file = File::open("./hellcheck.yml").unwrap();`](https://github.com/greyblake/hellcheck/blob/master/src/lib.rs#L26) even when you prototyping. It could provide useful error for others even without handling errors properly.

**Comment by greyblake** [comment]
Now it's required to specify `--file` option.
Also some error handling was improved here https://github.com/greyblake/hellcheck/commit/0498a8ecc92175bcfeb7799527e2bca6763ffe64

I am closing the issue.
